### ISSUE TITLE
ci: main is red on `cargo check --tests --features ci,nn,slow-tests` — compute_bounds not imported in vi/run_tests.rs (from #1305)

### ISSUE THREAD

**Issue by roninsightrx** [FeRx-NLME/ferx-core#1446]
## Summary

`origin/main` is red on one of the five `tools/preflight.sh check` feature sets:

```
cargo check --tests --no-default-features --features ci,nn,slow-tests
error[E0425]: cannot find function `compute_bounds` in this scope
  --> src/estimation/vi/run_tests.rs:1671
```

`src/estimation/vi/run.rs` imports `clamp_to_bounds, compute_mu_k, pack_params, pack_with_bounds, unpack_params, PackedStart` from `parameterization` but not `compute_bounds`, and the sibling test file calls it unqualified inside a `#[cfg(feature = "nn")]` test. The other four check commands are green.

Introduced by eaac92e4 (#1305). The `Check` CI job should be red on `main` for this set.

## Fix

One-line import (`use crate::estimation::parameterization::compute_bounds;` in the test sibling, or add it to `run.rs`'s import list). Already carried as commit `ec76430e fix(vi): import compute_bounds in the nn-gated VI test` on branch `worktree-saem-speed-e7-rm-scale`; happy to split it into its own PR.

Found while running the preflight matrix on merge branches during the SAEM speed programme (2026-09-18).
